---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update-cache: yes
      changed_when: False

  tasks:
    - import_tasks: tasks/packages.yml
